# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 13:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='description')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showreel', models.FileField(upload_to=b'')),
                ('clients', models.ManyToManyField(to='portfolios.Client')),
                ('testimonials', models.ManyToManyField(to='portfolios.Testimonial')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('product', models.CharField(max_length=20, verbose_name='product')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Role'),
        ),
    ]
