# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_auto_20170809_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(default='home', verbose_name='slug'),
            preserve_default=False,
        ),
    ]
