# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.CharField(max_length=400, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
    ]
