# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_auto_20170809_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='clients',
            field=models.ManyToManyField(blank=True, to='portfolios.Client'),
        ),
        migrations.AlterField(
            model_name='page',
            name='showreel',
            field=models.FileField(null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='page',
            name='testimonials',
            field=models.ManyToManyField(blank=True, to='portfolios.Testimonial'),
        ),
    ]
