# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_auto_20170809_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='showreel',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
