# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_auto_20170809_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='about'),
        ),
        migrations.AddField(
            model_name='page',
            name='subtitle',
            field=models.CharField(max_length=200, null=True, verbose_name='subtitle'),
        ),
    ]
