# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_auto_20170809_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='quote',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='quote'),
        ),
        migrations.AddField(
            model_name='page',
            name='quote_citation',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='quote citation'),
        ),
    ]
