# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0010_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Page')),
            ],
        ),
        migrations.RemoveField(
            model_name='text',
            name='page',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
