# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0013_auto_20170809_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='body',
            field=models.TextField(blank=True, verbose_name='body'),
        ),
    ]
