# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0014_auto_20170809_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='person',
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Client'),
        ),
    ]
