# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-09 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0017_auto_20170809_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
