# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0018_auto_20170809_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='video',
        ),
        migrations.AddField(
            model_name='client',
            name='content',
            field=models.TextField(default='', help_text='Embedded content (video or audio) that best represent your work done for this client', verbose_name='content'),
            preserve_default=False,
        ),
    ]
