# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0019_auto_20170810_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='featured',
            field=models.BooleanField(default=False, help_text='Whether or not to show in the bigger carousel', verbose_name='featured'),
        ),
        migrations.AlterField(
            model_name='client',
            name='content',
            field=models.TextField(blank=True, help_text='Embedded content (video or audio) that best represent your work done for this client', null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.CharField(help_text='Job title or the type of organisation', max_length=200, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Name of the client', max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='embeddedcontent',
            name='content',
            field=models.TextField(help_text='Paste in the embedded content from SoundCloud / YouTube etc.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='page',
            name='about',
            field=models.TextField(blank=True, help_text='Text shown in the About section', max_length=1000, null=True, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='page',
            name='clients',
            field=models.ManyToManyField(blank=True, help_text='Select the clients you would like to be listed in the Credits section', to='portfolios.Client'),
        ),
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, help_text='Short description for search engines', max_length=400, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='quote',
            field=models.TextField(blank=True, help_text='Something profound', max_length=1000, null=True, verbose_name='quote'),
        ),
        migrations.AlterField(
            model_name='page',
            name='quote_citation',
            field=models.CharField(blank=True, help_text='Some profound person', max_length=20, null=True, verbose_name='quote citation'),
        ),
        migrations.AlterField(
            model_name='page',
            name='showreel',
            field=models.FileField(blank=True, help_text='The showreel file', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='page',
            name='subtitle',
            field=models.CharField(help_text='Text to display below the title', max_length=200, null=True, verbose_name='subtitle'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(help_text='Title text to display', max_length=100, null=True, verbose_name='title'),
        ),
    ]
