# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0024_auto_20170810_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='number_of_featured_clients',
            field=models.IntegerField(default=5, help_text='The number of clients to show in the big carousel', verbose_name='number of featured clients'),
        ),
    ]
