# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0025_page_number_of_featured_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='link',
            field=models.URLField(blank=True, help_text="Link to this client's website.", null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='showreel_url',
            field=models.URLField(blank=True, help_text="The embedded video URL that best represent the work you've done for this client", null=True, verbose_name='showreel URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, help_text='URL of the embedded video content', null=True),
        ),
    ]
