# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0026_auto_20170810_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='mugshot',
            field=models.ImageField(blank=True, help_text='Your profile picture shown in the About section', null=True, upload_to=b''),
        ),
    ]
