# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0029_auto_20170810_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='footer_background',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='page',
            name='quote_background',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
