# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0030_auto_20170810_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='background',
            field=models.ImageField(blank=True, help_text='Background image to display in the carousel', null=True, upload_to='uploads/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mugshot',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='uploads/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='footer_background',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='mugshot',
            field=models.ImageField(blank=True, help_text='Your profile picture shown in the About section', null=True, upload_to='uploads/%Y-%m-%d/'),
        ),
        migrations.AlterField(
            model_name='page',
            name='quote_background',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y-%m-%d/'),
        ),
    ]
