# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0031_auto_20170810_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='showreel',
            field=models.FileField(blank=True, help_text='The showreel file', null=True, upload_to='uploads/%Y-%m-%d/'),
        ),
    ]
