# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0032_auto_20170810_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('kind', models.CharField(choices=[('Facebook', 'facebook-square'), ('LinkedIn', 'linkedin-square'), ('Twitter', 'twitter-square'), ('SoundCloud', 'soundcloud'), ('Spotify', 'spotify'), ('YouTube', 'youtube'), ('GitHub', 'github')], max_length=20, verbose_name='kind')),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='page',
            name='email',
            field=models.EmailField(blank=True, help_text='The email address people should contact you about this page', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='socialmedialink',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Page'),
        ),
    ]
