# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0035_auto_20170812_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='address',
            field=models.TextField(blank=True, help_text='Postal address', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='phone',
            field=models.CharField(blank=True, help_text='The contact phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='socialmedialink',
            name='kind',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('soundcloud', 'SoundCloud'), ('spotify', 'Spotify'), ('youtube', 'YouTube'), ('github', 'GitHub')], max_length=20, verbose_name='kind'),
        ),
    ]
