# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0036_auto_20170812_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='content',
        ),
    ]
