# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0037_remove_client_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
