# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0039_page_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('text', models.TextField(max_length=1000, verbose_name='text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/%Y-%m-%d/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Page')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
