# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0040_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embedded_content',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
